name: CI 

on:
  push:
    branches: [ "main" ]
 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
        
    - name: Build the Docker image
      run: docker build -t kush233/draw-backend:${{ github.sha }} .
    - name: Push to dockerhub
      run: docker push kush233/draw-backend:${{ github.sha }}

    - name: Clone ops-repo & push image tags
      env:  
        PAT: ${{ secrets.PAT }}
      run: | 
        git clone https://github.com/DoodleMesh/argo-backend
        cd argo-backend

        sed -i 's|image: kush233/draw-backend:.*|image: kush233/draw-backend:${{ github.sha }}|' deployment.yaml

        git config user.name "kushan23"
        git config user.email "kushan.arora23@gmail.com"
        git add .
        git commit -m "Updated image tag to ${{ github.sha }}"
        git push https://${PAT}@github.com/DoodleMesh/argo-backend.git main
 